version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      # Mapeia o código local para o container para desenvolvimento ao vivo
      - ./backend:/usr/src/app
      # Usa um volume anônimo para node_modules para evitar sobrescrever
      # os módulos instalados no container com os do host (se houver).
      - /usr/src/app/node_modules
    # O backend não precisa ser exposto ao host,
    # pois o Nginx (frontend) se comunicará com ele pela rede interna do Docker.
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8081:80" # Expõe a porta 80 do Nginx para a porta 8080 do seu PC
    volumes:
      # Mapeia os arquivos do frontend para desenvolvimento ao vivo
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend # Garante que o backend seja iniciado antes do frontend
    networks:
      - app-network

  cloudflared-tunnel:
  #http://kubernetes.docker.internal:20241 >> endereço do host no claudfare
   container_name: cloudfared-tunnel-jobs
   image: cloudflare/cloudflared:latest
   ports:
    - 20242:20241
   command: tunnel --no-autoupdate run
   restart: unless-stopped
   environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
   networks:
    - app-network

networks:
  app-network:
    driver: bridge
